name: ${project.name}
version: ${project.version}

ktor:
  application:
    modules:
      - me.blueb.ApplicationKt.module
  deployment:
    port: 9978
    host: 127.0.0.1

url: "https://aster.example.com/"
registrations: invite

database:
  host: localhost
  port: 5432
  db: aster
  user: ''
  password: ''