ALTER TABLE "user"
	ADD automated BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE "user"
	ALTER COLUMN "apId" TYPE VARCHAR(1025);
ALTER TABLE "user"
	ALTER COLUMN inbox TYPE VARCHAR(1025);
ALTER TABLE "user"
	ALTER COLUMN outbox TYPE VARCHAR(1025);
ALTER TABLE "user"
	ALTER COLUMN username TYPE VARCHAR(250);
ALTER TABLE "user"
	ALTER COLUMN bio TYPE VARCHAR(25000);
ALTER TABLE "user"
	ALTER COLUMN "location" TYPE VARCHAR(1025);
ALTER TABLE "user"
	ALTER COLUMN birthday TYPE VARCHAR(1025);
ALTER TABLE "user"
	ALTER COLUMN avatar TYPE VARCHAR(1025);
ALTER TABLE "user"
	ALTER COLUMN "avatarAlt" TYPE VARCHAR(25000);
ALTER TABLE "user"
	ALTER COLUMN banner TYPE VARCHAR(1025);
ALTER TABLE "user"
	ALTER COLUMN "bannerAlt" TYPE VARCHAR(25000);
