ALTER TABLE notification ALTER COLUMN note TYPE VARCHAR(125), ALTER COLUMN note DROP NOT NULL;
ALTER TABLE notification ALTER COLUMN relationship TYPE VARCHAR(125), ALTER COLUMN relationship DROP NOT NULL;
