CREATE TABLE IF NOT EXISTS "instance" (id VARCHAR(125) PRIMARY KEY, host VARCHAR(10000) NOT NULL, "name" VARCHAR(1000) NULL, description VARCHAR(10000) NULL, color VARCHAR(6) DEFAULT '000000' NOT NULL, icon VARCHAR(1000) NULL, "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updatedAt" TIMESTAMP NULL);
ALTER TABLE "instance" ADD CONSTRAINT unique_instance_id UNIQUE (id);
ALTER TABLE "instance" ADD CONSTRAINT unique_instance_host UNIQUE (host);
