CREATE TABLE IF NOT EXISTS emoji (id VARCHAR(125) PRIMARY KEY, "apId" VARCHAR(1025) NOT NULL, "name" VARCHAR(250) NOT NULL, host VARCHAR(500) NULL, src VARCHAR(1025) NOT NULL, "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, "updatedAt" TIMESTAMP NULL);
ALTER TABLE emoji ADD CONSTRAINT unique_emoji_id UNIQUE (id);
ALTER TABLE emoji ADD CONSTRAINT unique_emoji_apId UNIQUE ("apId");
