ALTER TABLE note ADD emojis TEXT[] DEFAULT ARRAY[]::text[] NOT NULL;
ALTER TABLE note ALTER COLUMN "to" TYPE TEXT[], ALTER COLUMN "to" SET DEFAULT ARRAY[]::text[];
ALTER TABLE note ALTER COLUMN tags TYPE TEXT[], ALTER COLUMN tags SET DEFAULT ARRAY[]::text[];
ALTER TABLE note ALTER COLUMN "createdAt" TYPE TIMESTAMP, ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
DROP INDEX IF EXISTS note_tag_index;
DROP INDEX IF EXISTS note_to_index;
