ALTER TABLE "user" ADD roles TEXT[] DEFAULT ARRAY[]::text[] NOT NULL;
ALTER TABLE "user" ADD emojis TEXT[] DEFAULT ARRAY[]::text[] NOT NULL;
ALTER TABLE "user" ALTER COLUMN "createdAt" TYPE TIMESTAMP, ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
