name: build-frontend.yml
on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Install pnpm
              run: npm install -g pnpm

            - name: Run aster.sh build-frontend
              run: ./aster.sh build-frontend
